version: '3.1'

services:
  mongodb:
    image: mongo:3.6
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    ports:
      - 8082:8082
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      VCAP_APP_PORT: 8082
  redis:
    image: redis:5
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander
    ports:
      - 8081:8081
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      - redis
